;;;###autoload
;; (set-face-background 'isearch "darkCyan")
;; (set-face-foreground 'isearch "white")
;; (set-face-background 'region "gray50")
;; (set-foreground-color "MistyRose3")
;; (set-background-color "Black")

(set-face-background 'ac-candidate-face "lightgray")
(set-face-background 'ac-selection-face "IndianRed")

(defun color-theme-loochao ()
  (interactive)
  (color-theme-install
   '(color-theme-loochao
     ((background-color . "Black")
      (background-mode . dark)
      (border-color . "Black")
      (cursor-color . "Sienna1")
      (foreground-color . "MistyRose")
      (mouse-color . "MistyRose"))
     (fringe ((t (:background "Black"))))
     (mode-line ((t (:foreground "#eeeeec" :background "DarkRed"))))
     (region ((t (:background "#5b3338"))))
     (font-lock-builtin-face ((t (:foreground "#3ac70a"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#999988"))))
     (font-lock-comment-face ((t (:foreground "#999988"))))     
     (font-lock-function-name-face ((t (:foreground "YellowGreen"))))     
     (font-lock-keyword-face ((t (:foreground "SlateBlue"))))     
     (font-lock-string-face ((t (:foreground "Orange"))))     
     (font-lock-type-face ((t (:foreground"#59842e"))))
     (font-lock-constant-face ((t (:foreground "AquaMarine"))))     
     (font-lock-variable-name-face ((t (:foreground "DarkSeaGreen"))))     
     (minibuffer-prompt ((t (:foreground "DarkSeaGreen" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-loochao)
